#!/bin/bash

FILE=~/tmp/_SUDDEN


while true
do
    if [[ -f "$FILE" ]]; then 
        #echo "check $FILE"
	echo "SUDDEN!!!"
    else 
	clear
	figlet KIA
	DATE=$(date +"%Y%m%d %H:%M:%S")
    fi

    sleep 3
done
